#!/bin/bash

set -e

source ~/venv-bastion/bin/activate

cd ~/src
git pull
flask db upgrade
bash ~/bin/wiki-importer.sh stop || true
bash ~/bin/wiki-importer.sh start || true
webservice --backend=kubernetes python3.7 stop && webservice --backend=kubernetes python3.7 start
