"""empty message

Revision ID: 15eef3b83c83
Revises: 8f4ad54966cd
Create Date: 2021-02-23 15:37:43.417824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15eef3b83c83'
down_revision = '8f4ad54966cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wiki_id', sa.Integer(), nullable=True),
    sa.Column('page_title', sa.String(length=255), nullable=True),
    sa.Column('imported_successfully', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wiki_id'], ['wiki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    # ### end Alembic commands ###
