"""empty message

Revision ID: 2afc23f9e61c
Revises: e059f5881de8
Create Date: 2020-10-13 19:21:52.237787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afc23f9e61c'
down_revision = 'e059f5881de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('clean_started', sa.Boolean(), nullable=True))
    op.add_column('wiki', sa.Column('import_started', sa.Boolean(), nullable=True))
    op.add_column('wiki', sa.Column('split_started', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'split_started')
    op.drop_column('wiki', 'import_started')
    op.drop_column('wiki', 'clean_started')
    # ### end Alembic commands ###
