"""empty message

Revision ID: 315143a05809
Revises: 15eef3b83c83
Create Date: 2021-02-23 16:38:28.521967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315143a05809'
down_revision = '15eef3b83c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('domain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'domain')
    # ### end Alembic commands ###
