"""empty message

Revision ID: 49afefa92614
Revises: d65b5d60ba55
Create Date: 2020-09-04 20:09:08.923220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49afefa92614'
down_revision = 'd65b5d60ba55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('is_clean', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'is_clean')
    # ### end Alembic commands ###
