"""empty message

Revision ID: 76224fbd5c12
Revises: e684868735f8
Create Date: 2020-09-05 19:41:17.418475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76224fbd5c12'
down_revision = 'e684868735f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
