"""empty message

Revision ID: 8627d32ee20c
Revises: 49afefa92614
Create Date: 2020-09-05 18:20:19.511441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8627d32ee20c'
down_revision = '49afefa92614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('clean_std_err', sa.Text(), nullable=True))
    op.add_column('wiki', sa.Column('clean_std_out', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'clean_std_out')
    op.drop_column('wiki', 'clean_std_err')
    # ### end Alembic commands ###
