"""empty message

Revision ID: 8f4ad54966cd
Revises: 2afc23f9e61c
Create Date: 2021-02-23 14:49:52.013150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f4ad54966cd'
down_revision = '2afc23f9e61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'split_std_err')
    op.drop_column('wiki', 'split_std_out')
    op.drop_column('wiki', 'clean_std_out')
    op.drop_column('wiki', 'is_split')
    op.drop_column('wiki', 'clean_started')
    op.drop_column('wiki', 'clean_std_err')
    op.drop_column('wiki', 'is_clean')
    op.drop_column('wiki', 'split_started')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('split_started', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('wiki', sa.Column('is_clean', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('wiki', sa.Column('clean_std_err', mysql.TEXT(), nullable=True))
    op.add_column('wiki', sa.Column('clean_started', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('wiki', sa.Column('is_split', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('wiki', sa.Column('clean_std_out', mysql.TEXT(), nullable=True))
    op.add_column('wiki', sa.Column('split_std_out', mysql.TEXT(), nullable=True))
    op.add_column('wiki', sa.Column('split_std_err', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
