"""empty message

Revision ID: cdb82dd30df7
Revises: 8627d32ee20c
Create Date: 2020-09-05 18:56:57.854813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb82dd30df7'
down_revision = '8627d32ee20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('split_std_err', sa.Text(), nullable=True))
    op.add_column('wiki', sa.Column('split_std_out', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'split_std_out')
    op.drop_column('wiki', 'split_std_err')
    # ### end Alembic commands ###
