SECRET_KEY: something
MESSAGES_DIR: ../messages
SQLALCHEMY_DATABASE_URI: mysql://root:password@localhost/wiki_importer
STATIC_URL: /static/
APPLICATION_ROOT: /
CONSUMER_KEY: 578b1051cad321218ceb392d8228375b
CONSUMER_SECRET: 860adffb679dfe4041e265e41937bb9e3006eb91
OAUTH_MWURI: https://meta.wikimedia.org/w
INCUBATOR_MWURI: https://incubator.wikimedia.org/w
TMP_DIR: ../data
CELERY_RESULT_BACKEND: redis://localhost:6379
CELERY_BROKER_URL: redis://localhost:6379
